task_id: "machine_operating_s2l"
data_path: "data/machine_operating_s2l.json"
model_name: "qwen3.5-9b"
prompt_name: "default"

max_examples: 30
n_responses: 1
agent_batch_size: 6
eval_batch_size: 16
resume: true

is_agentic: true
use_docker: true
server_image: "machine_operating_s2l:latest"
codex_server_image: "machine_operating_s2l_codex:latest"
max_time: 600

eval_lm: null

rollout_version: baseline
