task_id: "woocommerce_stock_alert_s2l"
data_path: "data/woocommerce_stock_alert_s2l.json"
model_name: "qwen3.5-9b"
prompt_name: "default"

max_examples: 30
n_responses: 3
agent_batch_size: 6
eval_batch_size: 16
resume: true

is_agentic: true
use_docker: true
server_image: "woocommerce_stock_alert_s2l:latest"
codex_server_image: "woocommerce_stock_alert_s2l_codex:latest"
max_time: 600

# rollout_version: "baseline"
agent_file: "tasks/woocommerce_stock_alert_s2l/agents/half_tools.py"
# eval_lm: "gemini-3-flash-preview"
